name: "Novafos login"
description: "An add-on to use Selenium web-driver to login to the Novafos website."
version: "1.0.0"
slug: "novafos-login-driver"
init: false
arch:
  - aarch64
ports:
  5000/tcp: 5000
startup: services
webui: http://[HOST]:[PORT:5000]/novafos-token/screenshots
stage: experimental